version: '3.1'

services:

  db:
    image: postgres:14.3
    container_name: tapdevdk-fastapi-example-dev
    restart: unless-stopped
    environment:
      POSTGRES_USER: fastapidevuser
      POSTGRES_PASSWORD: test1234
      POSTGRES_DB: fastapidevdb
    ports:
      - "5432:5432"