version: 2.1

executors:
  docker-publisher:
    environment:
      IMAGE_NAME: tapdevdk/fastapi-example # Docker Hub repo
    docker:
      - image: docker:20.10.14-git

jobs:
  build:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13 # required in order to prevent build errors in 'docker build'-step, with older versions of docker

      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/app.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=app -t $IMAGE_NAME .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/app.tar $IMAGE_NAME
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/app.tar
      - run:
          name: Archive Docker image
          command: docker save -o image.tar $IMAGE_NAME
          
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar

  publish-latest:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
            docker tag $IMAGE_NAME $IMAGE_NAME:latest
            docker push $IMAGE_NAME:latest
  
  publish-tag:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
            IMAGE_TAG=${CIRCLE_TAG/v/''}
            docker tag $IMAGE_NAME:latest $IMAGE_NAME:$IMAGE_TAG
            docker push $IMAGE_NAME:latest
            docker push $IMAGE_NAME:$IMAGE_TAG

workflows:
  version: 2

  # TODO: Remove this and use below commented version. its for development of the CircleCI config
  build-publish-latest:
    jobs:
      - build:
          context:
            - tapdev-prod
          filters:
            branches:
              only: main
      - publish-latest:
          context:
            - tapdev-prod
          requires:
            - build
          filters:
            branches:
              only: main

  build-publish-tag:
    jobs:
      - build:
          context:
            - tapdev-prod
          filters:
            tags:
              only: /^[\d]+\.[\d]+\.[\d]+/
            branches:
              ignore: /.*/
      - publish-tag:
          context:
            - tapdev-prod
          requires:
            - build
          filters:
            tags:
              only: /^[\d]+\.[\d]+\.[\d]+/
            branches:
              ignore: /.*/